name = "PlutoCanvasPlot"
uuid = "57876ffe-7b7d-4c51-befe-9eb7dc4baaca"
authors = ["Juergen Fuhrmann <juergen.fuhrmann@wias-berlin.de>"]
version = "0.0.5"

[deps]
Colors = "5ae59095-9a9b-59fe-a467-6f913c188581"
UUIDs = "cf7118a7-6976-5b1a-9a39-7adc72f591a4"

[compat]

Colors = "0.12"
julia  = "1.5"